# fly.toml file generated for appkata-gogs on 2020-11-02T10:25:32Z

app = "appkata-gogs"

[build]
image = "gogs/gogs"


[[services]]
internal_port = 3000
protocol      = "tcp"

    [services.concurrency]
    hard_limit = 25
    soft_limit = 20

    [[services.ports]]
    handlers = ["http"]
    port     = "80"

    [[services.ports]]
    handlers = ["tls", "http"]
    port     = "443"

    [[services.tcp_checks]]
    interval = 10000
    timeout  = 2000

[[services]]
internal_port = 22
protocol      = "tcp"

    [[services.ports]]
    handlers = []
    port     = 10022

    [[services.tcp_checks]]
    interval = 10000
    timeout  = 2000

[mounts]
source="data"
destination="/data"
